ci:
  autofix_commit_msg: 'chore: auto fixes from pre-commit hooks'
  autoupdate_commit_msg: 'chore: pre-commit automatic update'
  autoupdate_schedule: weekly
  skip: [ty]

repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49  # frozen: v0.16.5
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
  hooks:
  - id: codespell
    args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt", "-w"]

- repo: https://github.com/pycontribs/mirrors-prettier
  rev: c79518d33a81b378af7b186e99e360a2c9b63223  # frozen: v3.6.2
  hooks:
  - id: prettier
    types_or: [css, javascript]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: c4654a7e007c9619a5eb63c39a456572a0fa1851  # frozen: 0.38.0
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: 55c5b6a5439abd847613579c6924da750e8b78b2  # frozen: v0.8.0
  hooks:
  - id: add-license-headers
    files: '(src|doc/source/examples)/.*\.(py)'
    args:
    - --start_year=2021
    - --custom_license=Apache-2.0


- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: cef8b8350da46d8114c7e6b7272aebdccdf193ce  # frozen: v1.30.0
  hooks:
    - id: zizmor
      args:
      - "--no-progress"
      - "--persona=pedantic"

# Do not use this tool with proprietary ansys source code.
- repo: "https://github.com/djlint/djLint"
  rev: 76675b68608b5643655650bf461b7d2abb2e2a52  # frozen: v1.44.2
  hooks:
    - id: djlint-jinja
      types_or: ["html"]

- repo: https://github.com/astral-sh/ty-pre-commit
  rev: "015fb27be57627143ada502af8a2c9bb3ad3a7c2"  # frozen: v0.0.76
  hooks:
    - id: ty