# Copyright (C) 2021 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Minigallery extension for the Ansys Sphinx Theme.

This extension scans configured example directories — including both
**sphinx-gallery** ``.py`` example scripts and **Jupyter** ``.ipynb`` notebooks
— and builds a backreferences map that links every API object (class, function,
module) to the examples that reference it.

The resulting minigallery is automatically injected at the bottom of every
``autoapi`` class, function, and module page via the
``.. ansys-minigallery::`` directive, which is also available for manual use
anywhere in the documentation.

Configuration
-------------
Options are nested inside the existing ``ansys_sphinx_theme_autoapi`` theme
option dict inside ``html_theme_options``:

.. code-block:: python

    html_theme_options = {
        "ansys_sphinx_theme_autoapi": {
            ...
            # List of example directories relative to the repository root.
            "examples_dirs": [
                "doc/source/examples/sphinx-gallery",
                "doc/source/examples/nbsphinx",
            ],
            # Optional: fallback thumbnail (relative to srcdir or absolute).
            "gallery_default_thumbnail": "_static/pyansys_light_square.png",
        }
    }

The extension also reads two Sphinx config values directly (set automatically
by ``ansys_sphinx_theme.extension.autoapi``):

* ``ansys_gallery_dirs`` — list of example directory paths
* ``ansys_gallery_default_thumbnail`` — fallback thumbnail path

Directive
---------
.. code-block:: rst

    .. ansys-minigallery:: ansys_sphinx_theme.examples.samples.ExampleClass
       :heading: Gallery examples
       :no-heading:
"""

import ast
import base64
from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
from typing import Any, Dict, List, Optional

from docutils import nodes
from docutils.parsers.rst import Directive, directives
from docutils.statemachine import ViewList
from sphinx.application import Sphinx
from sphinx.util import logging as sphinx_logging

from ansys_sphinx_theme import __version__, ansys_favicon

logger = sphinx_logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class ExampleInfo:
    """Metadata about a single example that references an API object.

    Parameters
    ----------
    title : str
        Human-readable title of the example (extracted from docstring or
        markdown heading).
    doc_path : str
        Sphinx docname (relative to ``srcdir``, without extension) used for
        the ``:link:`` in the card.
    source_type : str
        Either ``"gallery"`` (sphinx-gallery ``.py``) or ``"notebook"``
        (Jupyter ``.ipynb``).
    src_file_abs : str
        Absolute path to the source file (``.py`` or ``.ipynb``).  Used to
        resolve the thumbnail lazily at directive render time, after
        sphinx-gallery has had a chance to generate its thumbnail images.
    thumbnail_uri : str
        Srcdir-relative path to the thumbnail image.  Empty string means
        "resolve lazily at render time" (used for gallery examples whose
        thumbnail is generated by sphinx-gallery during ``builder-inited``,
        which runs *after* our scan).
    """

    title: str
    doc_path: str
    source_type: str
    src_file_abs: str
    thumbnail_uri: str = ""


# ---------------------------------------------------------------------------
# AST helpers
# ---------------------------------------------------------------------------


def _fqn_set_from_source(source_code: str) -> set:
    """Return the set of fully-qualified names referenced in *source_code*.

    The function performs a two-pass analysis:

    1. Collect all ``import`` and ``from … import`` statements and build a
       local-alias → FQN mapping.
    2. Walk all ``Name`` and ``Attribute`` nodes, resolving them through the
       alias map to recover the original FQN.
    3. For every ``from X import Y`` import, attempt to dynamically resolve
       the *canonical* definition location (``Y.__module__ + "." +
       Y.__qualname__``) via :func:`_canonical_fqns_from_alias_map`.  This
       means that ``from ansys.dyna.core import Deck`` correctly produces
       *both* ``ansys.dyna.core.Deck`` (the import path) and
       ``ansys.dyna.core.deck.Deck`` (where autoapi generates the page).

    Parameters
    ----------
    source_code : str
        Python source code to analyse.

    Returns
    -------
    set[str]
        Every fully-qualified name encountered (imports + usages), including
        canonical definition locations resolved via the live Python runtime.
    """
    try:
        tree = ast.parse(source_code)
    except SyntaxError:
        return set()

    # Pass 1 — build alias map: local_name → fqn
    # Also keep track of which aliases came from "from X import Y" so we can
    # attempt runtime resolution.
    alias_map: Dict[str, str] = {}
    # Maps import-path FQN → (module_str, attr_name) for runtime resolution
    from_import_map: Dict[str, tuple] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                local = alias.asname if alias.asname else alias.name
                alias_map[local] = alias.name
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            for alias in node.names:
                if alias.name == "*":
                    continue
                local = alias.asname if alias.asname else alias.name
                fqn = f"{module}.{alias.name}" if module else alias.name
                alias_map[local] = fqn
                from_import_map[fqn] = (module, alias.name)

    # Pass 2 — collect referenced names
    refs: set = set(alias_map.values())  # every import is already a reference
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            resolved = alias_map.get(node.id)
            if resolved:
                refs.add(resolved)
        elif isinstance(node, ast.Attribute):
            # Walk a.b.c chains to rebuild the dotted name
            parts: List[str] = []
            n = node
            while isinstance(n, ast.Attribute):
                parts.append(n.attr)
                n = n.value
            if isinstance(n, ast.Name) and n.id in alias_map:
                parts.append(n.id)
                parts.reverse()
                root_fqn = alias_map[parts[0]]
                remainder = ".".join(parts[1:])
                full = f"{root_fqn}.{remainder}" if remainder else root_fqn
                refs.add(full)
                # Also index every intermediate prefix so module-level lookups work
                segs = root_fqn.split(".") + parts[1:]
                for i in range(2, len(segs) + 1):
                    refs.add(".".join(segs[:i]))

    # Pass 3 — resolve canonical FQNs via the live runtime
    refs.update(_canonical_fqns_from_alias_map(from_import_map))

    return refs


def _canonical_fqns_from_alias_map(from_import_map: Dict[str, tuple]) -> set:
    """Resolve the canonical definition location for every ``from X import Y``.

    Python re-exports are common in large packages: ``ansys.dyna.core``
    re-exports ``Deck`` from ``ansys.dyna.core.deck``, so
    ``from ansys.dyna.core import Deck`` gives an AST FQN of
    ``ansys.dyna.core.Deck``, but autoapi generates a page for the definition
    site ``ansys.dyna.core.deck.Deck``.

    This function uses :mod:`importlib` to import each module and reads
    ``obj.__module__`` and ``obj.__qualname__`` to find where the object is
    actually defined.  Both the import-path FQN and the canonical FQN are
    returned so the minigallery matches either form.

    Failures (package not installed, import error, missing attribute) are
    silently skipped — the AST FQN is always kept regardless.

    Parameters
    ----------
    from_import_map : dict[str, tuple[str, str]]
        Mapping of ``import_fqn → (module_str, attr_name)`` collected during
        AST scanning.

    Returns
    -------
    set[str]
        Additional canonical FQNs to add alongside the AST-derived refs.
    """
    import importlib

    extra: set = set()
    for import_fqn, (module_str, attr_name) in from_import_map.items():
        if not module_str:
            continue
        try:
            mod = importlib.import_module(module_str)
            obj = getattr(mod, attr_name, None)
            if obj is None:
                continue
            obj_module = getattr(obj, "__module__", None)
            obj_qualname = getattr(obj, "__qualname__", None)
            if not obj_module or not obj_qualname:
                continue
            canonical = f"{obj_module}.{obj_qualname}"
            if canonical != import_fqn:
                extra.add(canonical)
                # Also add all intermediate prefixes so module-level pages match
                parts = canonical.split(".")
                for i in range(2, len(parts) + 1):
                    extra.add(".".join(parts[:i]))
        except Exception:  # noqa: BLE001
            # ImportError, AttributeError, or any other runtime error — skip
            pass
    return extra


# ---------------------------------------------------------------------------
# File-type parsers
# ---------------------------------------------------------------------------


def _parse_gallery_py(path: Path) -> tuple:
    """Parse a sphinx-gallery ``.py`` example file.

    Parameters
    ----------
    path : ~pathlib.Path
        Absolute path to the ``.py`` file.

    Returns
    -------
    tuple[str, set[str]]
        The human-readable title and the set of fully-qualified names
        referenced in the file.
    """
    source = path.read_text(encoding="utf-8")

    # Default: use the file stem
    title = path.stem.replace("_", " ").replace("-", " ").title()

    # Try to extract the title from the module-level docstring.
    # sphinx-gallery convention: first non-empty, non-underline line.
    try:
        tree = ast.parse(source)
        docstring = ast.get_docstring(tree) or ""
        for line in docstring.splitlines():
            stripped = line.strip()
            if stripped and not set(stripped).issubset(set("=-~^")):
                title = stripped
                break
    except SyntaxError:
        pass

    return title, _fqn_set_from_source(source)


def _parse_notebook(path: Path) -> tuple:
    """Parse a Jupyter notebook (``.ipynb``) file.

    Parameters
    ----------
    path : ~pathlib.Path
        Absolute path to the ``.ipynb`` file.

    Returns
    -------
    tuple[str, set[str], bytes | None]
        Human-readable title, set of fully-qualified names referenced in the
        notebook, and raw bytes of the first image output found (or ``None``).
    """
    try:
        nb = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return path.stem, set(), None

    cells = nb.get("cells", [])
    title = path.stem.replace("_", " ").replace("-", " ").title()
    fqns: set = set()
    thumbnail_data: Optional[bytes] = None
    title_found = False

    for cell in cells:
        cell_type = cell.get("cell_type", "")
        source_lines = cell.get("source", [])
        source = "".join(source_lines) if isinstance(source_lines, list) else str(source_lines)

        if cell_type == "markdown" and not title_found:
            for line in source.splitlines():
                stripped = line.strip()
                if stripped.startswith("# ") and not stripped.startswith("## "):
                    title = stripped[2:].strip()
                    title_found = True
                    break

        elif cell_type == "code":
            fqns.update(_fqn_set_from_source(source))

            # Extract the first image output as the thumbnail
            if thumbnail_data is None:
                for output in cell.get("outputs", []):
                    out_data = output.get("data", {})
                    for mime in ("image/png", "image/jpeg"):
                        if mime in out_data:
                            raw = out_data[mime]
                            if isinstance(raw, list):
                                raw = "".join(raw)
                            try:
                                thumbnail_data = base64.b64decode(raw)
                            except Exception:
                                pass
                            break
                    if thumbnail_data is not None:
                        break

    return title, fqns, thumbnail_data


# ---------------------------------------------------------------------------
# Thumbnail helpers
# ---------------------------------------------------------------------------


def _default_thumb_path(default_thumb: str) -> str:
    """Return the srcdir-relative path for the configured default thumbnail.

    Parameters
    ----------
    default_thumb : str
        Value of ``ansys_gallery_default_thumbnail`` config key.  May be an
        absolute-root URI (``/_static/...``), a bare ``_static/``-prefixed
        path, or a plain filename.

    Returns
    -------
    str
        Path relative to the Sphinx ``srcdir`` root (no leading ``/``).
    """
    if default_thumb:
        # Strip a leading slash so the path is always srcdir-relative
        return default_thumb.lstrip("/")
    # ansys favicon is a suitable default thumbnail for examples that don't configure one
    return ansys_favicon.lstrip("/")


def _gallery_thumb_path(
    py_path: Path,
    sphinx_gallery_conf: Optional[dict],
    default_thumb_path: str,
    srcdir: str,
) -> str:
    """Return the srcdir-relative path for a sphinx-gallery example thumbnail.

    Sphinx-gallery writes thumbnails to
    ``<gallery_dir>/Folder/images/thumb/<stem>_thumb.png`` inside ``srcdir``.
    We locate the file and return its srcdir-relative path.  If the file
    does not yet exist (first build) we fall back to *default_thumb_path*.

    Parameters
    ----------
    py_path : ~pathlib.Path
        Absolute path to the source ``.py`` file.
    sphinx_gallery_conf : dict | None
        Value of ``sphinx_gallery_conf`` from the Sphinx config, if present.
    default_thumb_path : str
        Srcdir-relative fallback returned when the thumbnail cannot be found.
    srcdir : str
        Absolute path to the Sphinx source directory.

    Returns
    -------
    str
        Srcdir-relative path to the thumbnail (no leading ``/``).
    """
    if not sphinx_gallery_conf:
        return default_thumb_path

    examples_dirs = sphinx_gallery_conf.get("examples_dirs", [])
    gallery_dirs = sphinx_gallery_conf.get("gallery_dirs", [])
    if isinstance(examples_dirs, str):
        examples_dirs = [examples_dirs]
    if isinstance(gallery_dirs, str):
        gallery_dirs = [gallery_dirs]

    srcdir_path = Path(srcdir).resolve()
    stem = py_path.stem

    for examples_dir, gallery_dir in zip(examples_dirs, gallery_dirs):
        # Resolve examples_dir — may be relative to srcdir (e.g. "../examples")
        ex_dir = Path(examples_dir)
        if not ex_dir.is_absolute():
            ex_dir = (srcdir_path / ex_dir).resolve()

        try:
            rel_in_ex = py_path.parent.relative_to(ex_dir)
        except ValueError:
            continue  # this py file doesn't belong to this examples_dir

        # Resolve gallery_dir — usually srcdir-relative (e.g. "auto_examples")
        gdir = Path(gallery_dir)
        if not gdir.is_absolute():
            gdir = (srcdir_path / gdir).resolve()

        # sphinx-gallery thumbnail: <gallery_dir>/<subfolder>/images/thumb/sphx_glr_<stem>_thumb.png
        thumb_abs = gdir / rel_in_ex / "images" / "thumb" / f"sphx_glr_{stem}_thumb.png"
        if thumb_abs.exists():
            try:
                return str(thumb_abs.relative_to(srcdir_path)).replace(os.sep, "/")
            except ValueError:
                # gallery_dir is outside srcdir — return absolute URI as fallback
                return str(thumb_abs).replace(os.sep, "/")

    return default_thumb_path


def _gallery_output_docname(
    py_file: Path,
    sphinx_gallery_conf: Optional[dict],
    srcdir: str,
) -> Optional[str]:
    """Return the Sphinx docname for the *built* gallery page of a ``.py`` file.

    sphinx-gallery writes its RST output files into the configured
    ``gallery_dirs``, not alongside the source ``.py`` files.  The docname of
    the rendered page is therefore ``<gallery_dirs[i]>/<stem>``, not
    ``<examples_dirs[i]>/<stem>``.

    Parameters
    ----------
    py_file : ~pathlib.Path
        Absolute path to the source ``.py`` file.
    sphinx_gallery_conf : dict | None
        Value of ``sphinx_gallery_conf`` from the Sphinx config.
    srcdir : str
        Absolute path to the Sphinx source directory.

    Returns
    -------
    str | None
        Srcdir-relative docname (no extension, no leading ``/``), or ``None``
        when the mapping cannot be determined.
    """
    if not sphinx_gallery_conf:
        return None

    examples_dirs = sphinx_gallery_conf.get("examples_dirs", [])
    gallery_dirs = sphinx_gallery_conf.get("gallery_dirs", [])
    if isinstance(examples_dirs, str):
        examples_dirs = [examples_dirs]
    if isinstance(gallery_dirs, str):
        gallery_dirs = [gallery_dirs]

    srcdir_path = Path(srcdir).resolve()

    for examples_dir, gallery_dir in zip(examples_dirs, gallery_dirs):
        # Resolve examples_dir (may be srcdir-relative or absolute)
        ex_dir = Path(examples_dir)
        if not ex_dir.is_absolute():
            ex_dir = (srcdir_path / ex_dir).resolve()

        try:
            rel_to_ex = py_file.relative_to(ex_dir)
        except ValueError:
            continue

        # gallery_dir is also srcdir-relative or absolute
        gal_dir = Path(gallery_dir)
        if not gal_dir.is_absolute():
            gal_dir = gallery_dir.rstrip("/")
        else:
            gal_dir = os.path.relpath(str(gal_dir), str(srcdir_path)).replace(os.sep, "/")

        stem = rel_to_ex.with_suffix("").as_posix()
        return f"{str(gal_dir).rstrip('/')}/{stem}"

    return None


def _autoapi_package_prefixes(config: Any, srcdir: str) -> List[str]:
    """Derive the top-level Python package prefix(es) from ``autoapi_dirs``.

    For each directory listed in ``autoapi_dirs``, this function walks *up*
    from that directory collecting directory names while consecutive
    ``__init__.py`` files are present.  The resulting dotted name is the
    importable package prefix that autoapi will document.

    For example, given ``autoapi_dirs = ["../../src/ansys_sphinx_theme/examples"]``
    (relative to ``srcdir``), where both ``ansys_sphinx_theme/`` and
    ``ansys_sphinx_theme/examples/`` contain ``__init__.py`` but ``src/``
    does not, the returned prefix is ``"ansys_sphinx_theme.examples"``.

    Parameters
    ----------
    config : ~sphinx.config.Config
        Sphinx config object.
    srcdir : str
        Absolute Sphinx source directory path.

    Returns
    -------
    list[str]
        Sorted list of dotted package prefixes (e.g.
        ``["ansys_sphinx_theme.examples"]``).
    """
    autoapi_dirs: List[str] = list(getattr(config, "autoapi_dirs", []) or [])
    prefixes: List[str] = []
    srcdir_path = Path(srcdir).resolve()

    for d in autoapi_dirs:
        p = Path(d)
        if not p.is_absolute():
            p = (srcdir_path / p).resolve()
        if not p.is_dir():
            continue

        # Walk upward collecting package components while __init__.py exists.
        parts: List[str] = []
        cur = p
        while (cur / "__init__.py").exists():
            parts.append(cur.name)
            cur = cur.parent

        if parts:
            parts.reverse()
            prefixes.append(".".join(parts))

    return sorted(set(prefixes))


def scan_examples(app: Sphinx) -> None:
    """Scan all configured example directories and build the backrefs map.

    This function is connected to the ``builder-inited`` Sphinx event.  It
    populates ``app.env.ansys_gallery_backrefs``, a ``dict`` mapping every
    fully-qualified name to a list of :class:`ExampleInfo` objects representing
    the examples that reference it.

    Parameters
    ----------
    app : ~sphinx.application.Sphinx
        Application instance for rendering the documentation.
    """
    config_dirs: List[str] = list(getattr(app.config, "ansys_gallery_dirs", []) or [])
    default_thumb = str(getattr(app.config, "ansys_gallery_default_thumbnail", "") or "")

    if not config_dirs:
        logger.debug("ansys-minigallery: no example directories configured; skipping scan.")
        return

    if not hasattr(app.env, "ansys_gallery_backrefs"):
        app.env.ansys_gallery_backrefs = {}  # type: ignore[attr-defined]
    if not hasattr(app.env, "ansys_gallery_example_fqns"):
        # Reverse map: docname → sorted list of FQNs used in that example.
        app.env.ansys_gallery_example_fqns = {}  # type: ignore[attr-defined]
    if not hasattr(app.env, "ansys_gallery_notebook_docnames"):
        # Set of docnames that correspond to Jupyter notebooks (.ipynb).
        # The source-read hook must NOT inject RST directives into these because
        # their source[0] is raw notebook JSON, not RST.
        app.env.ansys_gallery_notebook_docnames = set()  # type: ignore[attr-defined]
    # Derive and cache the autoapi-documented package prefixes so the
    # AnsysAPIReferencesDirective can filter FQNs to only the project's own API.
    if not hasattr(app.env, "ansys_gallery_package_prefixes"):
        app.env.ansys_gallery_package_prefixes = _autoapi_package_prefixes(  # type: ignore[attr-defined]
            app.config, app.srcdir
        )

    backrefs = app.env.ansys_gallery_backrefs
    example_fqns = app.env.ansys_gallery_example_fqns
    notebook_docnames = app.env.ansys_gallery_notebook_docnames
    thumb_dir = Path(app.srcdir) / "_static" / "ansys-gallery" / "thumbs"
    thumb_dir.mkdir(parents=True, exist_ok=True)

    # Repository root: assume docs live two levels below it (e.g. doc/source/).
    root_dir = Path(app.srcdir).resolve().parent.parent
    sphinx_gallery_conf: Optional[dict] = getattr(app.config, "sphinx_gallery_conf", None)
    # nbsphinx_thumbnails maps docname → thumbnail path (configured in conf.py)
    nbsphinx_thumbnails: dict = dict(getattr(app.config, "nbsphinx_thumbnails", {}) or {})
    default_path = _default_thumb_path(default_thumb)

    total_files = 0

    for dir_str in config_dirs:
        # Resolve relative to repo root first, then srcdir
        dir_path = (root_dir / dir_str).resolve()
        if not dir_path.is_dir():
            dir_path = (Path(app.srcdir) / dir_str).resolve()
        if not dir_path.is_dir():
            logger.warning(
                f"ansys-minigallery: examples directory not found: {dir_str!r}. Skipping."
            )
            continue

        # ---- sphinx-gallery .py files ----------------------------------------
        for py_file in sorted(dir_path.rglob("*.py")):
            if py_file.name.startswith("_") or py_file.name == "conf.py":
                continue

            title, fqns = _parse_gallery_py(py_file)

            # The built page lives in gallery_dirs, not alongside the source .py.
            # Use sphinx_gallery_conf to find the correct output docname.
            docname = _gallery_output_docname(py_file, sphinx_gallery_conf, str(app.srcdir))
            if docname is None:
                # Fallback: use the source .py path as the docname
                try:
                    rel = py_file.relative_to(Path(app.srcdir))
                    docname = str(rel.with_suffix("")).replace(os.sep, "/")
                except ValueError:
                    logger.debug(f"ansys-minigallery: cannot determine docname for {py_file}")
                    continue

            thumb_uri = _gallery_thumb_path(
                py_file, sphinx_gallery_conf, default_path, str(app.srcdir)
            )
            info = ExampleInfo(
                title=title,
                doc_path=docname,
                source_type="gallery",
                # thumbnail_uri is intentionally left empty here.
                # sphinx-gallery generates thumbnails during its own builder-inited
                # hook, which runs AFTER ours (autoapi is listed in extensions before
                # sphinx_gallery.gen_gallery).  We resolve it lazily at directive
                # run() time, when the thumbnail file is guaranteed to exist.
                src_file_abs=str(py_file),
                thumbnail_uri="",
            )

            for fqn in fqns:
                backrefs.setdefault(fqn, [])
                if not any(e.doc_path == docname for e in backrefs[fqn]):
                    backrefs[fqn].append(info)

            # Reverse map: record every FQN discovered in this example file.
            if fqns:
                existing = example_fqns.get(docname, set())
                existing.update(fqns)
                example_fqns[docname] = existing

            total_files += 1

        # ---- Jupyter notebooks -----------------------------------------------
        for nb_file in sorted(dir_path.rglob("*.ipynb")):
            if nb_file.name.startswith(".") or ".ipynb_checkpoints" in str(nb_file):
                continue

            title, fqns, thumb_data = _parse_notebook(nb_file)

            try:
                rel = nb_file.relative_to(Path(app.srcdir))
                docname = str(rel.with_suffix("")).replace(os.sep, "/")
            except ValueError:
                logger.debug(f"ansys-minigallery: cannot make {nb_file} relative to srcdir")
                continue

            # Priority for thumbnails:
            #  1. First image/png or image/jpeg output embedded in the notebook JSON
            #     (only present when the notebook was pre-executed with outputs saved).
            #  2. nbsphinx_thumbnails mapping (configured in conf.py).
            #  3. Configured default fallback.
            #
            # Note: scan_examples runs at builder-inited, before nbsphinx executes
            # notebooks, so cell outputs on disk are only available when the notebook
            # was committed with outputs already embedded.
            if thumb_data is not None:
                thumb_name = nb_file.stem + ".png"
                thumb_abs = thumb_dir / thumb_name
                thumb_abs.write_bytes(thumb_data)
                # srcdir-relative path (no leading /)
                thumb_uri = str(thumb_abs.relative_to(Path(app.srcdir))).replace(os.sep, "/")
            else:
                # Check nbsphinx_thumbnails: keys are docnames, values are
                # _static-relative or absolute paths.
                nb_thumb_configured = nbsphinx_thumbnails.get(docname, "")
                thumb_uri = (
                    _default_thumb_path(nb_thumb_configured)
                    if nb_thumb_configured
                    else default_path
                )

            info = ExampleInfo(
                title=title,
                doc_path=docname,
                source_type="notebook",
                src_file_abs=str(nb_file),
                thumbnail_uri=thumb_uri,
            )

            for fqn in fqns:
                backrefs.setdefault(fqn, [])
                if not any(e.doc_path == docname for e in backrefs[fqn]):
                    backrefs[fqn].append(info)

            # Reverse map: record every FQN discovered in this notebook.
            if fqns:
                existing = example_fqns.get(docname, set())
                existing.update(fqns)
                example_fqns[docname] = existing

            # Track notebook docnames so the source-read hook can skip them.
            notebook_docnames.add(docname)

            total_files += 1

    n_objects = len(backrefs)
    n_refs = sum(len(v) for v in backrefs.values())
    logger.info(
        f"ansys-minigallery: scanned {total_files} example file(s); "
        f"indexed {n_refs} reference(s) across {n_objects} API object(s)."
    )


# ---------------------------------------------------------------------------
# env-merge-info hook (parallel read safety)
# ---------------------------------------------------------------------------


def env_merge_info(
    app: Sphinx,
    env: Any,
    docnames: List[str],
    other: Any,
) -> None:
    """Merge backrefs from a parallel-read sub-environment.

    Parameters
    ----------
    app : ~sphinx.application.Sphinx
        Application instance.
    env : ~sphinx.environment.BuildEnvironment
        The main environment being built.
    docnames : list[str]
        Docnames processed by the sub-environment.
    other : ~sphinx.environment.BuildEnvironment
        The sub-environment whose data should be merged.
    """
    if not hasattr(other, "ansys_gallery_backrefs"):
        return
    if not hasattr(env, "ansys_gallery_backrefs"):
        env.ansys_gallery_backrefs = {}
    for fqn, examples in other.ansys_gallery_backrefs.items():
        env.ansys_gallery_backrefs.setdefault(fqn, [])
        existing = {e.doc_path for e in env.ansys_gallery_backrefs[fqn]}
        for ex in examples:
            if ex.doc_path not in existing:
                env.ansys_gallery_backrefs[fqn].append(ex)
                existing.add(ex.doc_path)

    # Merge the reverse map (docname → fqn set)
    if hasattr(other, "ansys_gallery_example_fqns"):
        if not hasattr(env, "ansys_gallery_example_fqns"):
            env.ansys_gallery_example_fqns = {}
        for docname, fqns in other.ansys_gallery_example_fqns.items():
            existing_fqns = env.ansys_gallery_example_fqns.get(docname, set())
            existing_fqns.update(fqns)
            env.ansys_gallery_example_fqns[docname] = existing_fqns

    # Merge the notebook docnames set.
    if hasattr(other, "ansys_gallery_notebook_docnames"):
        if not hasattr(env, "ansys_gallery_notebook_docnames"):
            env.ansys_gallery_notebook_docnames = set()
        env.ansys_gallery_notebook_docnames.update(other.ansys_gallery_notebook_docnames)

    # Package prefixes are config-derived and identical across sub-envs;
    # just ensure the main env has a value.
    if not hasattr(env, "ansys_gallery_package_prefixes") and hasattr(
        other, "ansys_gallery_package_prefixes"
    ):
        env.ansys_gallery_package_prefixes = other.ansys_gallery_package_prefixes


# ---------------------------------------------------------------------------
# Directive
# ---------------------------------------------------------------------------


def _srcdir_to_docrel(srcdir_path: str, docname: str) -> str:
    """Convert a srcdir-relative path to one relative to *docname*'s directory.

    Sphinx resolves ``.. image::`` (and ``:img-top:``) relative to the
    **source file** of the current document, not the site root.  Autoapi
    pages can be several directories deep, so we must account for depth.

    Parameters
    ----------
    srcdir_path : str
        Path relative to the Sphinx ``srcdir`` root (no leading ``/``).
        E.g. ``_static/pyansys_light_square.png`` or
        ``examples/gallery-examples/images/thumb/foo_thumb.png``.
    docname : str
        Current Sphinx docname, e.g.
        ``examples/api/examples/sample_func/func``.

    Returns
    -------
    str
        Relative path from the docname's directory to *srcdir_path*,
        using forward slashes.
    """
    from pathlib import PurePosixPath

    doc_dir = str(PurePosixPath(docname).parent)
    if doc_dir == ".":
        # top-level docname — no directory depth to escape
        return srcdir_path
    rel = os.path.relpath(srcdir_path, doc_dir)
    return rel.replace(os.sep, "/")


def _resolve_thumbnail(ex: "ExampleInfo", srcdir: str, default_path: str, config: Any) -> str:
    """Return the srcdir-relative thumbnail path for *ex*, resolving it freshly.

    For sphinx-gallery examples this is called at directive ``run()`` time
    rather than at ``builder-inited``, because sphinx-gallery writes its
    thumbnail PNGs during its own ``builder-inited`` hook which — due to
    extension load order — fires *after* minigallery's scan hook.

    For Jupyter notebooks, if no embedded output was stored during scanning
    we consult ``nbsphinx_thumbnails`` from the Sphinx config before falling
    back to the project default.

    Parameters
    ----------
    ex : ExampleInfo
        The example whose thumbnail to resolve.
    srcdir : str
        Absolute path to the Sphinx source directory.
    default_path : str
        Srcdir-relative fallback (e.g. ``_static/pyansys_light_square.png``).
    config : ~sphinx.config.Config
        The live Sphinx config object (``env.config``).

    Returns
    -------
    str
        Srcdir-relative path to the thumbnail image (no leading ``/``).
    """
    if ex.source_type == "gallery":
        # Re-resolve from sphinx_gallery_conf every time so we always pick up
        # the generated thumbnail regardless of when scan_examples ran.
        sgconf: Optional[dict] = getattr(config, "sphinx_gallery_conf", None)
        return _gallery_thumb_path(Path(ex.src_file_abs), sgconf, default_path, srcdir)

    # --- notebook ---
    # Use the thumbnail that was already extracted from embedded outputs (if any)
    if ex.thumbnail_uri:
        return ex.thumbnail_uri

    # Fall back to nbsphinx_thumbnails config
    nb_thumbs: dict = dict(getattr(config, "nbsphinx_thumbnails", {}) or {})
    configured = nb_thumbs.get(ex.doc_path, "")
    if configured:
        return _default_thumb_path(configured)

    return default_path


class AnsysMinigalleryDirective(Directive):
    """Render a minigallery of examples that reference an API object.

    The directive accepts one required argument: the fully-qualified name of
    the Python object to look up in the backreferences map.

    .. code-block:: rst

        .. ansys-minigallery:: ansys_sphinx_theme.examples.samples.ExampleClass
           :heading: Gallery examples

    Options
    -------
    heading : str
        Custom heading text.  Defaults to ``"Gallery examples"``.
    no-heading : flag
        Suppress the heading entirely.

    The directive resolves fuzzy matches: if the FQN provided matches *any*
    indexed key as a suffix or prefix, those examples are included.  This
    means that ``ExampleClass`` and
    ``ansys_sphinx_theme.examples.samples.ExampleClass`` both resolve to the
    same set of examples.
    """

    required_arguments = 1
    optional_arguments = 0
    option_spec = {
        "heading": directives.unchanged,
        "no-heading": directives.flag,
    }
    has_content = False

    def run(self) -> List[nodes.Node]:
        """Execute the directive and return docutils nodes."""
        env = self.state.document.settings.env
        fqn = self.arguments[0].strip()
        backrefs: Dict[str, List[ExampleInfo]] = getattr(env, "ansys_gallery_backrefs", {})

        # Fuzzy FQN matching: allow both short names and fully qualified names
        examples: List[ExampleInfo] = []
        seen_paths: set = set()
        for key, infos in backrefs.items():
            matched = (
                key == fqn
                or key.endswith(f".{fqn}")
                or fqn.endswith(f".{key}")
                or fqn == key.split(".")[-1]
            )
            if matched:
                for ex in infos:
                    if ex.doc_path not in seen_paths:
                        examples.append(ex)
                        seen_paths.add(ex.doc_path)

        if not examples:
            # Return silently — no gallery section if no examples exist
            return []

        result_nodes: List[nodes.Node] = []

        # --- Heading (rubric) ---
        if "no-heading" not in self.options:
            heading_text = self.options.get("heading", "Gallery examples")
            rubric = nodes.rubric(text=heading_text)
            rubric["classes"].append("ansys-minigallery-heading")
            result_nodes.append(rubric)

        # --- Build a sphinx-design grid via nested RST parsing ---
        rst_lines: List[str] = []
        rst_lines.append(".. grid:: 4 5 6 6")
        rst_lines.append("   :gutter: 2")
        rst_lines.append("   :class-container: ansys-minigallery-grid")
        rst_lines.append("")

        for ex in examples:
            # Resolve thumbnail now (directive run() time), not at scan time.
            # sphinx-gallery thumbnails are only on disk after sphinx-gallery's
            # own builder-inited hook, which fires after our scan_examples.
            default_path = _default_thumb_path(
                str(getattr(env.config, "ansys_gallery_default_thumbnail", "") or "")
            )
            thumb_srcrel = _resolve_thumbnail(ex, env.srcdir, default_path, env.config)
            # Convert srcdir-relative path to docname-relative for Sphinx image resolution
            img_rel = _srcdir_to_docrel(thumb_srcrel, env.docname)
            rst_lines.append("   .. grid-item-card::")
            rst_lines.append(f"      :img-top: {img_rel}")
            rst_lines.append(f"      :link: /{ex.doc_path}")
            rst_lines.append("      :link-type: doc")
            rst_lines.append("      :class-card: ansys-minigallery-card")
            rst_lines.append("      :class-img-top: ansys-minigallery-thumb")
            rst_lines.append("      :shadow: sm")
            rst_lines.append("")
            rst_lines.append(f"      {ex.title}")
            rst_lines.append("")

        # Parse RST lines into docutils nodes
        vl = ViewList()
        source = env.docname
        for i, line in enumerate(rst_lines):
            vl.append(line, source, i)

        container = nodes.container()
        container["classes"].append("ansys-minigallery")
        self.state.nested_parse(vl, self.content_offset, container)
        result_nodes.append(container)

        return result_nodes


# ---------------------------------------------------------------------------
# API-references directive  (reverse of minigallery)
# ---------------------------------------------------------------------------


class AnsysAPIReferencesDirective(Directive):
    """Render a bulleted list of API objects referenced in the current example.

    This is the *reverse* of ``.. ansys-minigallery::``.  Whereas the
    minigallery shows—on an API page—which examples use that object, this
    directive shows—on an example page—which API objects are imported/used.

    The directive reads the ``ansys_gallery_example_fqns`` map that
    ``scan_examples`` (``builder-inited``) has already populated, and emits
    a ``.. rubric::`` heading plus a ``.. py:obj::`` bullet list for every
    indexed FQN that actually has an autoapi page (i.e. the FQN is also a key
    in ``ansys_gallery_backrefs``, confirming autoapi knows about it).

    Usage
    -----
    .. code-block:: rst

        .. ansys-api-references::
           :heading: API references used in this example
           :no-heading:

    Options
    -------
    heading : str
        Custom heading text.  Defaults to ``"API references"``.  Ignored if
        ``no-heading`` is given.
    no-heading : flag
        Suppress the heading entirely.
    """

    required_arguments = 0
    optional_arguments = 0
    option_spec = {
        "heading": directives.unchanged,
        "no-heading": directives.flag,
    }
    has_content = False

    def run(self) -> List[nodes.Node]:
        """Execute the directive and return docutils nodes."""
        env = self.state.document.settings.env
        docname: str = env.docname

        # Look up which FQNs were found in this example file.
        example_fqns: Dict[str, Any] = getattr(env, "ansys_gallery_example_fqns", {})
        raw_fqns: set = example_fqns.get(docname, set())

        # Only surface FQNs that are indexed in backrefs — those are the ones
        # that have a corresponding autoapi page.
        backrefs: Dict[str, Any] = getattr(env, "ansys_gallery_backrefs", {})
        known_fqns = set(backrefs.keys())

        # Restrict to FQNs that belong to the project's own documented package(s).
        # This filters out third-party libraries (numpy, matplotlib, etc.) that
        # happen to be imported in an example but are not documented via autoapi.
        pkg_prefixes: List[str] = list(getattr(env, "ansys_gallery_package_prefixes", []))
        if pkg_prefixes:
            own_fqns = {
                fqn
                for fqn in raw_fqns
                if any(fqn == p or fqn.startswith(p + ".") for p in pkg_prefixes)
            }
        else:
            # No prefixes derived — fall back to showing all indexed FQNs.
            own_fqns = raw_fqns

        api_fqns = sorted(own_fqns & known_fqns)

        if not api_fqns:
            return []

        result_nodes: List[nodes.Node] = []

        # --- Heading (rubric) ---
        if "no-heading" not in self.options:
            heading_text = self.options.get("heading", "API references")
            rubric = nodes.rubric(text=heading_text)
            rubric["classes"].append("ansys-api-references-heading")
            result_nodes.append(rubric)

        # --- Bullet list of :py:obj: cross-references ---
        # Build the RST inline and parse it so Sphinx resolves the x-refs.
        rst_lines: List[str] = []
        for fqn in api_fqns:
            rst_lines.append(f"* :py:obj:`{fqn}`")

        vl = ViewList()
        source = docname
        for i, line in enumerate(rst_lines):
            vl.append(line, source, i)

        container = nodes.container()
        container["classes"].append("ansys-api-references")
        self.state.nested_parse(vl, self.content_offset, container)
        result_nodes.append(container)

        return result_nodes


# ---------------------------------------------------------------------------
# Extension setup
# ---------------------------------------------------------------------------


def _inject_api_refs_in_example(app: Sphinx, docname: str, source: List[str]) -> None:
    """Append ``.. ansys-api-references::`` to sphinx-gallery RST pages.

    This ``source-read`` hook fires for every source file Sphinx reads.
    For ``.ipynb`` notebooks the ``source-read`` event fires with the **raw
    notebook JSON** as ``source[0]``, not RST — injecting RST into JSON would
    corrupt the notebook.  We therefore skip any docname that was recorded as
    a notebook by :func:`scan_examples`.

    For sphinx-gallery ``.py`` examples, sphinx-gallery converts the script to
    an ``.rst`` file on disk; Sphinx reads that RST via the normal pipeline and
    ``source-read`` fires with RST, so injection is safe.

    Parameters
    ----------
    app : ~sphinx.application.Sphinx
        Application instance.
    docname : str
        Sphinx docname being read.
    source : list[str]
        One-element mutable list containing the raw source text (RST for
        sphinx-gallery pages, JSON for ``.ipynb`` notebook pages).
    """
    example_fqns: Dict[str, Any] = getattr(app.env, "ansys_gallery_example_fqns", {})
    if docname not in example_fqns:
        return

    # Never inject into notebooks — their source[0] is raw JSON, not RST.
    notebook_docnames: set = getattr(app.env, "ansys_gallery_notebook_docnames", set())
    if docname in notebook_docnames:
        return

    # Only append if there are actually indexed FQNs to show.
    backrefs: Dict[str, Any] = getattr(app.env, "ansys_gallery_backrefs", {})
    if not (example_fqns[docname] & set(backrefs.keys())):
        return

    source[0] = source[0].rstrip() + "\n\n.. ansys-api-references::\n"


def _add_api_refs_to_notebook_doctree(app: Sphinx, doctree: nodes.document) -> None:
    """Append API-references nodes to a notebook page's doctree.

    Unlike sphinx-gallery pages (which produce RST that Sphinx reads via the
    normal ``source-read`` pipeline), nbsphinx converts ``.ipynb`` notebooks
    directly to docutils nodes *without* going through ``source-read``.  The
    ``doctree-read`` event fires after nbsphinx has built the doctree, so this
    is the correct place to append extra nodes for notebook pages.

    The function builds:

    * A ``rubric`` heading ("API references").
    * A ``bullet_list`` of ``pending_xref`` nodes — one per API object.  Sphinx
      resolves these references during its normal cross-reference resolution
      pass, exactly like any ``:py:obj:`` role in hand-written RST.

    Parameters
    ----------
    app : ~sphinx.application.Sphinx
        Application instance.
    doctree : docutils.nodes.document
        The doctree that was just read.  The docname for the current document
        is available via ``app.env.docname``.
    """
    from sphinx.addnodes import pending_xref

    env = app.env
    docname: str = env.docname

    # Only act on notebook pages.
    notebook_docnames: set = getattr(env, "ansys_gallery_notebook_docnames", set())
    if docname not in notebook_docnames:
        return

    example_fqns: Dict[str, Any] = getattr(env, "ansys_gallery_example_fqns", {})
    raw_fqns: set = example_fqns.get(docname, set())
    if not raw_fqns:
        return

    backrefs: Dict[str, Any] = getattr(env, "ansys_gallery_backrefs", {})
    known_fqns: set = set(backrefs.keys())

    pkg_prefixes: List[str] = list(getattr(env, "ansys_gallery_package_prefixes", []))
    if pkg_prefixes:
        own_fqns = {
            fqn
            for fqn in raw_fqns
            if any(fqn == p or fqn.startswith(p + ".") for p in pkg_prefixes)
        }
    else:
        own_fqns = raw_fqns

    api_fqns = sorted(own_fqns & known_fqns)
    if not api_fqns:
        return

    # --- Heading ---
    rubric = nodes.rubric(text="API references")
    rubric["classes"].append("ansys-api-references-heading")

    # --- Bullet list of pending cross-references ---
    bullet_list = nodes.bullet_list()
    for fqn in api_fqns:
        xref = pending_xref(
            "",
            nodes.literal(fqn, fqn, classes=["xref", "py", "py-obj"]),
            refdomain="py",
            reftype="obj",
            reftarget=fqn,
            modname=None,
            classname=None,
            refexplicit=True,
        )
        para = nodes.paragraph()
        para += xref
        item = nodes.list_item()
        item += para
        bullet_list += item

    container = nodes.container()
    container["classes"].append("ansys-api-references")
    container += bullet_list

    doctree += [rubric, container]


def _inject_function_minigallery(app: Sphinx, docname: str, source: List[str]) -> None:
    """Append ``.. ansys-minigallery::`` to autoapi function own-pages.

    Instead of a custom Jinja template (which overwrites autoapi's built-in
    function template and breaks pydata-sphinx-theme's ``'fullname'`` HTML
    page-context lookup), this ``source-read`` hook appends the directive text
    directly to the raw RST that Sphinx has just read from disk.  By the time
    any source file is read, ``scan_examples`` (``builder-inited``) has already
    populated ``env.ansys_gallery_backrefs``, so the directive's ``run()``
    method will resolve correctly.

    Parameters
    ----------
    app : ~sphinx.application.Sphinx
        Application instance.
    docname : str
        Sphinx docname being read (e.g. ``api/mypackage/MyClass``).
    source : list[str]
        One-element mutable list containing the raw RST source text.
    """
    autoapi_root: str = str(getattr(app.config, "autoapi_root", "api") or "api").rstrip("/")
    if not docname.startswith(autoapi_root + "/"):
        return

    content = source[0]

    # Detect function own-pages: they contain ``.. py:function::`` but neither
    # ``.. py:class::`` nor ``.. py:module::`` (those are handled in the Jinja
    # templates for class.rst / module.rst).
    if ".. py:function::" not in content:
        return
    if ".. py:class::" in content or ".. py:module::" in content:
        return

    # Extract the fully-qualified name from the directive line, e.g.:
    #   .. py:function:: ansys.module.my_func(args) -> RetType
    match = re.search(r"\.\. py:function:: ([A-Za-z_][A-Za-z0-9_.]*)", content)
    if not match:
        return

    fqn = match.group(1)
    source[0] = content.rstrip() + f"\n\n.. ansys-minigallery:: {fqn}\n"


def setup(app: Sphinx) -> Dict[str, Any]:
    """Register the minigallery extension with Sphinx.

    Parameters
    ----------
    app : ~sphinx.application.Sphinx
        Application instance for rendering the documentation.

    Returns
    -------
    dict[str, Any]
        Extension metadata.
    """
    # Config values — populated by ansys_sphinx_theme.extension.autoapi from
    # html_theme_options["ansys_sphinx_theme_autoapi"]["examples_dirs"]
    app.add_config_value("ansys_gallery_dirs", [], "env")
    app.add_config_value("ansys_gallery_default_thumbnail", "", "env")

    app.add_directive("ansys-minigallery", AnsysMinigalleryDirective)
    app.add_directive("ansys-api-references", AnsysAPIReferencesDirective)
    app.connect("builder-inited", scan_examples)
    app.connect("source-read", _inject_api_refs_in_example)
    app.connect("source-read", _inject_function_minigallery)
    app.connect("doctree-read", _add_api_refs_to_notebook_doctree)
    app.connect("env-merge-info", env_merge_info)

    return {
        "version": __version__,
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
